name: test-f
on:
  push:
    branches: [ tp3 ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v2
    - name: compilation  
      run: make

    - name: tests
      run: |
        echo -e "### test1\n$ ./tp3 < tests/test1.txt\n~~~\n" > fonctionnel.md
        ./tp3 < tests/test1.txt >> fonctionnel.md
        echo -e "\n~~~\n### test2\n$ ./tp3 -i < tests/test1.txt\n~~~\n" >> fonctionnel.md
        ./tp3 -i < tests/test1.txt >> fonctionnel.md
        echo -e "\n~~~\n### test3\n$ ./tp3 -d < tests/test1.txt\n~~~\n" >> fonctionnel.md
        ./tp3 -d < tests/test1.txt >> fonctionnel.md
        echo -e "\n~~~\n### test4\n$ ./tp3 -s < tests/test1.txt\n~~~\n" >> fonctionnel.md
        ./tp3 -s < tests/test1.txt >> fonctionnel.md
        echo -e "\n~~~\n### test5\n$ ./tp3 -t < tests/test1.txt\n~~~\n" >> fonctionnel.md
        ./tp3 -t < tests/test1.txt >> fonctionnel.md
        echo -e "\n~~~\n### test6\n$ ./tp3 -d -s -i -t < tests/test2.txt\n~~~\n" >> fonctionnel.md
        ./tp3 -d -s -i -t < tests/test2.txt >> fonctionnel.md
        echo -e "\n~~~\n### test7\n$ ./tp3 < tests/test2.txt\n~~~\n" >> fonctionnel.md
        ./tp3 < tests/test2.txt >> fonctionnel.md
        echo -e "\n~~~"
        
    - name: push
      uses: actions-x/commit@v1
      with:
        name: GitHub Actions Autocommitter
        branch: tp3
        files: fonctionnel.md