name: test-c
on:
  push:
    branches: [ tp3 ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v2
    - name: compilation  
      run: make > compilation.md

    - name: push
      uses: actions-x/commit@v1
      with:
        name: GitHub Actions Autocommitter
        branch: tp3
        files: compilation.md