name: test-c
on:
  push:
    branches:
      - tp3

jobs:
  job_1:
    name: job 1
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v2
    - name: compilation  
      run: make > test.md
